Public Enum statusEnum
    SYSTEM_DOWN
    SYSTEM_INITIALIZED
    SYSTEM_PAUSED
    SYSTEM_UNPAUSED
    SYSTEM_INITIALIZING
    GENERIC_MESSAGE
    WARNING_MESSAGE_ADD
    WARNING_MESSAGE_REMOVE
End Enum
